spring.application.name=auth-user-service

spring.cloud.config.fail-fast=true
spring.cloud.config.retry.max-attempts=20
spring.cloud.config.retry.initial-interval=3000
spring.cloud.config.retry.max-interval=10000
spring.cloud.config.retry.multiplier=1.5

spring.cloud.config.request-connect-timeout=10000
spring.cloud.config.request-read-timeout=60000

spring.config.import=configserver:http://config-server:8888