server:
  port: 0

spring:
  application:
    name: cart-service

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/mousiq_cart_db}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true