spring.application.name=eureka-server

server.port=8761

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.value}

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO
